version: "3.8"

services:
  
  db:
    container_name: postgres-14.5
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    volumes:
      - db-data:/var/lib/postgresql/data
# Essas configurações abaixo podem ser utilizadas para evitar erro com o uso de memória RAM pelo postgres
#     - type: tmpfs
#       target: /dev/shm
    expose: 
      - 5432
    ports:
      - "5432:5432"
    networks:
      - authentication

volumes:
  db-data:

networks:
  authentication:

